# Generated by Django 3.2.7 on 2021-09-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos_team/%Y/%m/%d')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('designation', models.CharField(max_length=255, verbose_name='Профессия')),
                ('facebook_link', models.URLField(unique=True)),
                ('twitter_link', models.URLField(unique=True)),
                ('google_plus_link', models.URLField(unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
