# Generated by Django 3.2.7 on 2021-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255, verbose_name='Названия авто.')),
                ('state', models.CharField(choices=[('CH', 'Чуйская область'), ('TL', 'Талаская область'), ('IS', 'Иссык-Кульская область'), ('NR', 'Нарынская область'), ('OS', 'Ошская область'), ('BT', 'Баткенская область'), ('DJ', 'Джалал Абадская область')], max_length=2, verbose_name='Выбор области')),
                ('color', models.CharField(choices=[('RD', 'Красный'), ('BL', 'Синий'), ('YL', 'Жёлтый'), ('GR', 'Зелёный'), ('BK', 'Чёрный'), ('PG', 'Розовый'), ('WH', 'Белый')], max_length=2, verbose_name='цвет')),
                ('model', models.CharField(max_length=200, verbose_name='Модель авто')),
                ('year', models.DateField(auto_now_add=True, verbose_name='Дата авто')),
                ('body_style', models.CharField(choices=[('SDN', 'Седан'), ('SRT', 'Спорт-Авто'), ('SUV', 'Внедорожник'), ('HTC', 'Хэтчбек'), ('PCP', 'Пикап')], help_text='Выбор кузова обязательно', max_length=3, unique=True, verbose_name='Тип кузова')),
                ('fuel_type', models.CharField(choices=[('BNZ', 'Бензин'), ('DZL', 'Дизель'), ('B-G', 'Бензин-Газ'), ('ELC', 'Электро')], max_length=3, verbose_name='Тип топливо')),
                ('kilometers', models.PositiveBigIntegerField(verbose_name='Пробег авто.')),
                ('doors', models.CharField(choices=[('6', 'Шести дверная'), ('5', 'Пяти дверная'), ('4', 'Четырех дверная'), ('3', 'Трех дверная'), ('2', 'Двух дверная'), ('1', 'Одно дверная'), ('7', 'Больше 6 дверей')], max_length=1, verbose_name='Количество двере.')),
                ('condition', models.CharField(choices=[('NW', 'Новая'), ('PR', 'Отличная'), ('GD', 'Хорошое'), ('BD', 'Удовлетворительно')], max_length=2, verbose_name='Состояния авто')),
                ('description', models.TextField(help_text='Максимум 1000 символов', max_length=1000, verbose_name='Описания авто')),
                ('car_photo', models.ImageField(help_text='Оязательно заполнения картинки!', unique_for_date=True, upload_to='car_photo/Y%/%m/%d', verbose_name='Фото авто')),
                ('car_photo_1', models.ImageField(blank=True, null=True, unique_for_date=True, upload_to='car_photo_1/Y%/%m/%d')),
                ('car_photo_2', models.ImageField(blank=True, null=True, unique_for_date=True, upload_to='car_photo_2/Y%/%m/%d')),
                ('car_photo_3', models.ImageField(blank=True, null=True, unique_for_date=True, upload_to='car_photo_3/Y%/%m/%d')),
                ('passengers', models.PositiveSmallIntegerField(default=0, verbose_name='Кол пассажиров.')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендации.')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Дата публикации.')),
            ],
        ),
    ]
