# Generated by Django 3.2.7 on 2021-09-11 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('CH', 'Чуйская область'), ('TL', 'Талаская область'), ('IS', 'Иссык-Кульская область'), ('NR', 'Нарынская область'), ('OS', 'Ошская область'), ('BT', 'Баткенская область'), ('DJ', 'Джалал Абадская область')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('RD', 'Красный'), ('BL', 'Синий'), ('YL', 'Жёлтый'), ('GR', 'Зелёный'), ('BK', 'Чёрный'), ('PG', 'Розовый'), ('WH', 'Белый')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='year')),
                ('condition', models.CharField(choices=[('NW', 'Новая'), ('PR', 'Отличная'), ('GD', 'Хорошое'), ('BD', 'Удовлетворительно')], max_length=100)),
                ('description', models.TextField()),
                ('car_image', models.ImageField(upload_to='car_image/%Y/%m/%d')),
                ('car_image_1', models.ImageField(blank=True, upload_to='car_image/%Y/%m/%d')),
                ('car_image_2', models.ImageField(blank=True, upload_to='car_image/%Y/%m/%d')),
                ('car_image_3', models.ImageField(blank=True, upload_to='car_image/%Y/%m/%d')),
                ('car_image_4', models.ImageField(blank=True, upload_to='car_image/%Y/%m/%d')),
                ('features', models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=100)),
                ('body_style', models.CharField(choices=[('SDN', 'Седан'), ('SRT', 'Спорт-Авто'), ('SUV', 'Внедорожник'), ('HTC', 'Хэтчбек'), ('PCP', 'Пикап')], max_length=100)),
                ('engine', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('interior', models.CharField(max_length=255)),
                ('miles', models.PositiveIntegerField()),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='4', max_length=255)),
                ('passengers', models.IntegerField(default=3)),
                ('vin_no', models.CharField(max_length=17)),
                ('millage', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('BNZ', 'Бензин'), ('DZL', 'Дизель'), ('B-G', 'Бензин-Газ'), ('ELC', 'Электро')], max_length=100)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
