# Generated by Django 3.2.7 on 2021-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='millage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='no_of_owners',
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MN', 'MANUAL'), ('AU', 'AUTO/ROBOT')], max_length=255),
        ),
    ]
