# Generated by Django 3.2.7 on 2021-09-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210911_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('SEDAN', 'Седан'), ('SPORT-CAR', 'Спорт-Авто'), ('SUV', 'Внедорожник'), ('HATCH-BACK', 'Хэтчбек'), ('PICK-UP', 'Пикап')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('RED', 'Красный'), ('BLUE', 'Синий'), ('YELLOW', 'Жёлтый'), ('GREEN', 'Зелёный'), ('BLACK', 'Чёрный'), ('PIG', 'Розовый'), ('WHITE', 'Белый')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Новая'), ('PERFECT', 'Отличная'), ('GOOD', 'Хорошое'), ('BAD', 'Удовлетворительно')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('CHUY', 'Чуйская область'), ('TALAS', 'Талаская область'), ('ISSYK-KULL', 'Иссык-Кульская область'), ('NARYN', 'Нарынская область'), ('OSH', 'Ошская область'), ('BATKEN', 'Баткенская область'), ('DJALA-ABAD', 'Джалал Абадская область')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTO', 'AUTO/ROBOT')], max_length=255),
        ),
    ]
