# Generated by Django 3.2.7 on 2021-09-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210911_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='for_rent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='for_sale',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
