# Generated by Django 3.2.7 on 2021-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210913_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='price_for_rent',
        ),
        migrations.AddField(
            model_name='car',
            name='price_for_sale',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
